var d = document.getElementById("content__icon--93");
var dtx = d.getContext("2d");
dtx.beginPath();
dtx.arc(75, 75, 70, 4.7, 3.32 * Math.PI);
dtx.lineWidth = 3;
dtx.strokeStyle = "#606caf";
dtx.stroke();

var d = document.getElementById("content__icon--84");
var dtx = d.getContext("2d");
dtx.beginPath();
dtx.arc(75, 75, 70, 4.7, 3.20 * Math.PI);
dtx.lineWidth = 3;
dtx.strokeStyle = "#606caf";
dtx.stroke();

var d = document.getElementById("content__icon--97");
var dtx = d.getContext("2d");
dtx.beginPath();
dtx.arc(75, 75, 70, 4.7, 3.4 * Math.PI);
dtx.lineWidth = 3;
dtx.strokeStyle = "#606caf";
dtx.stroke();

var d = document.getElementById("content__icon--83");
var dtx = d.getContext("2d");
dtx.beginPath();
dtx.arc(75, 75, 70, 4.7, 3.18 * Math.PI);
dtx.lineWidth = 3;
dtx.strokeStyle = "#606caf";
dtx.stroke();

var canvas = document.getElementById("content__graph");
var dtx = canvas.getContext("2d");
var ctx = canvas.getContext("2d");
dtx.beginPath();
dtx.arc(24, 22, 20, 0, 2 * Math.PI);
dtx.lineWidth = 3;
dtx.strokeStyle = "#8A8686";
dtx.stroke();
ctx.moveTo(24, 250);
ctx.lineTo(24, 43);
ctx.lineWidth = 1;
ctx.strokeStyle = "#8A8686";
ctx.stroke();
dtx.beginPath();
dtx.arc(24, 268, 20, 0, 2 * Math.PI);
dtx.lineWidth = 3;
dtx.strokeStyle = "#8A8686";
dtx.stroke();

var canvas = document.getElementById("content__graph--two");
var dtx = canvas.getContext("2d");
var ctx = canvas.getContext("2d");
dtx.beginPath();
dtx.arc(24, 85, 20, 0, 2 * Math.PI);
dtx.lineWidth = 3;
dtx.strokeStyle = "#8A8686";
dtx.stroke();
ctx.moveTo(24, 300);
ctx.lineTo(24, 105);
ctx.lineWidth = 1;
ctx.strokeStyle = "#8A8686";
ctx.stroke();
dtx.beginPath();
dtx.arc(24, 320, 20, 0, 2 * Math.PI);
dtx.lineWidth = 3;
dtx.strokeStyle = "#8A8686";
dtx.stroke();
ctx.moveTo(24, 545);
ctx.lineTo(24, 340);
ctx.lineWidth = 1;
ctx.strokeStyle = "#8A8686";
ctx.stroke();
dtx.beginPath();
dtx.arc(24, 565, 20, 0, 2 * Math.PI);
dtx.lineWidth = 3;
dtx.strokeStyle = "#8A8686";
dtx.stroke();

var canvas = document.getElementById("content__graph--three");
var dtx = canvas.getContext("2d");
var ctx = canvas.getContext("2d");
dtx.beginPath();
dtx.arc(24, 60, 20, 0, 2 * Math.PI);
dtx.lineWidth = 3;
dtx.strokeStyle = "#8A8686";
dtx.stroke();
ctx.moveTo(24, 279);
ctx.lineTo(24, 80);
ctx.lineWidth = 1;
ctx.strokeStyle = "#8A8686";
ctx.stroke();
dtx.beginPath();
dtx.arc(24, 300, 20, 0, 2 * Math.PI);
dtx.lineWidth = 3;
dtx.strokeStyle = "#8A8686";
dtx.stroke();